name: test

on: 
  push:
  workflow_dispatch:

jobs:
  hello_world_job:
    name: A job to say hello
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Hello world action step
      #   uses: ./ # Uses an action in the root directory
      #   id: hello
      #   with:
      #     who-to-greet: 'Mona the Octocat'
      # # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
      # action.yml
      - name: Dump env
        run: env
      - name: Authenticate CLI with OIDC
        shell: bash
        run: |-
          OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
          JWT=$(echo $OIDC_TOKEN | jq -j '.value')
          echo $OIDC_TOKEN
          curl -sLS "https://cold-heron-19.deno.dev" -H "Authorization: Bearer $JWT"